### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'wildcard' of undefined

### ISSUE THREAD

**Issue by josephfinlayson** [tjunnone/npm-check-updates#101]
For command `npm-check-updates /^eslint-/  `

```
Unhandled rejection TypeError: Cannot read property 'wildcard' of undefined
    at getPreferredWildcard (/home/joe/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm-check-updates/lib/versionmanager.js:396:21)
    at Object.upgradeDependencies (/home/joe/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm-check-updates/lib/versionmanager.js:130:20)
    at /home/joe/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:40:39
    at tryCatcher (/home/joe/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/joe/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/joe/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/joe/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/joe/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/joe/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/joe/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

**Comment by metaraine** [comment]
Please provide the version of npm-check-updates you are using, as well as a list of dependencies in your package.json. Thanks!

**Comment by metaraine** [comment]
Nevermind, I'm reproducing it now! I'll investigate.

**Comment by metaraine** [comment]
Found and fixed! Thanks.

`npm install npm-check-updates@unstable`

**Comment by josephfinlayson** [comment]
Sorry I didn't get back to you!

**Comment by a7madgamal** [comment]
Thanks for the fix. but when should it be available in the stable branch?

**Comment by metaraine** [comment]
v2 was released 9 days ago, so it's in stable now!

If you are can still reproduce after upgrading to the latest stable `ncu`, please post the error and your dependencies.

**Comment by a7madgamal** [comment]
never mind I think because I have 'npm-check-updates' in my package file at older version and it couldn't update itself so I just installed the newest version and it works now and updated it's own version lol
Inception style :D

**Comment by a7madgamal** [comment]
after reading the issue title carefully I was having another issue: Unhandled rejection 404 or something like this!

**Comment by metaraine** [comment]
If you have a different error, please create a new issue and include the error message as well as your dependencies. 

(Are you sure the 404 wasn't fixed in v2.1.0, as described in #117?)

**Comment by a7madgamal** [comment]
no everything is fine I guess :)

**Comment by metaraine** [comment]
Yay!
