### ISSUE TITLE
Unhandled rejection Error: 404 Not Found

### ISSUE THREAD

**Issue by Kikobeats** [tjunnone/npm-check-updates#117]
```
$ ncu -g
Unhandled rejection Error: 404 Not Found
    at Object.ensureErrorObject (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:465:22)
    at PromiseArray.__hardReject__.PromiseArray._reject (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise_array.js:109:19)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:575:21)
    at Promise._settlePromises (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:448:13)
```

**Comment by Climax777** [comment]
I get the same problem. Would love to know where the 404 occurs

**Comment by metaraine** [comment]
It appears that npm's REST API now returns the string `"404 Not Found"` instead of the previous JSON `{ statusCode: 404, ... }`, some time within the last 24 hours. Figures that I had some logic checking err.statusCode to determine if an installed module was not found in npm.

Try the latest stable ncu `v2.1.0` and see if that fixes the issue. Thanks!

(In general, always provide your `package.json` when submitting issues, or in the case of `ncu -g`, paste the output from `npm ls -g --depth=0`.)

**Comment by kahwee** [comment]
I can't reproduce this in `v2.1.0`.
