### ISSUE TITLE
Unhandled rejection Error: 404 Not Found

### ISSUE THREAD

**Issue by kud** [tjunnone/npm-check-updates#120]
```
Unhandled rejection Error: 404 Not Found
    at Object.ensureErrorObject (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:465:22)
    at PromiseArray.__hardReject__.PromiseArray._reject (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise_array.js:109:19)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:575:21)
    at Promise._settlePromises (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Did you already get this?

`2.0.0-alpha.16`

**Comment by metaraine** [comment]
Highly recommended to upgrade to `2.1.0`!

**Comment by kud** [comment]
```
$ npm install -g npm-check-updates

npm-check-updates@2.1.0 /Users/kud/.nvm/versions/node/v0.12.7/lib/node_modules/npm-check-updates
```
```
$ ncu --version
2.0.0-alpha.16
```

**Comment by kud** [comment]
Okay there's something wrong with nvm apparently.

```
/Users/kud/.nvm/versions/node/v0.12.7/lib/node_modules/npm-check-updates/bin/npm-check-updates --version
2.1.0
```

**Comment by kud** [comment]
For those who have the same problem,

`$ rm -rf /usr/local/bin/ncu && npm uninstall npm-check-updates -g && npm install npm-check-updates -g`
