### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by Blitz2145** [tjunnone/npm-check-updates#130]
Ran the following command:
`$ ncu`
```
$ ncu --version
$ 2.2.1
```

Got this:
### Traceback
```
Unhandled rejection TypeError: Cannot read property 'then' of undefined
    at programRunLocal (/usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:305:19)
    at programRun (/usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:267:50)
    at tryCatcher (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by Blitz2145** [comment]
Looks like it happens when there is no `package.json` in the current directory. Maybe throw in an error message saying something to that effect. `ncu` is working now that I'm in the right directory, thanks!

**Comment by metaraine** [comment]
Thanks for reporting! I totally agree. I put a more descriptive error message in `v2.2.2`.
