### ISSUE TITLE
Missing proto-list error

### ISSUE THREAD

**Issue by adam-lynch** [tjunnone/npm-check-updates#144]
```shell
» ncu

module.js:340
    throw err;
          ^
Error: Cannot find module 'proto-list'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Digital\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\node_modules\conf
ig-chain\index.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Digital\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\lib\config\core.j
s:1:72)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

(Latest version on Windows)

**Comment by metaraine** [comment]
Hi Adam. Thanks for reporting. It looks like the error is originating from npm. What version of npm do you have installed? 

(I'm wondering if there might be an issue with ncu using a different version of npm locally than the system version which builds out the node_modules folder...)

One thing you can try is deleting your npm_modules folder and running `npm install` again then try `ncu`.

**Comment by patriksima** [comment]
Hello, its problem on Ubuntu 14.04 LTS with npm version 1.3.10. All depencies don't install. Proto-list, lodash.* etc.

**Comment by metaraine** [comment]
Hi Patrik. So you are getting the exact same error as Adam? I don't have enough information to troubleshoot yet.

**Comment by patriksima** [comment]
Yes, I have. I tried to install missing module manually, but list of missing depencies is too long.

**Comment by adam-lynch** [comment]
I haven't been near my Windows machine since I created this but just in
case it might help, I tried the latest and 2.0.0. Broken for both.

**Comment by metaraine** [comment]
Hi Patrik. Does this error happen when you delete the entire node_modules folder and run `npm install`?

**Comment by patriksima** [comment]
No.
```
cd whatever folder
npm cache clean
npm install
npm install -g npm-check-updates
ncu
```
ncu shows error - missing module XYZ
if I install missing module manually and run ncu again. it shows another error missing module

It seems it doesn't install any dependencies.

**Comment by patriksima** [comment]
Btw. In my Win 8.1 (i have dualboot) it works without any problems.

**Comment by metaraine** [comment]
Thanks for the additional information. As yet, I am unable to reproduce. I installed node v0.12.0 and npm v1.3.10 and then ran the latest version of `ncu`, but it worked fine for me.

Will you post a list of the dependencies in your package.json? I will try running it on the exact same list of dependencies as you.

**Comment by metaraine** [comment]
An additional note: npm-check-updates doesn't actually install dependencies, it just checks for updates and then modifies your package.json. The stack trace that Adam provided shows that the error is originating from npm. The only npm commands that npm-check-updates calls are `load`, `view`, and `list`. Hopefully this helps anyone that is able to debug further. 

If you can reproduce the problem, your best bet may be to go into the npm-check-updates source code of your install and troubleshoot with console.log's from there. It will be difficult for me to contribute much more without the ability to reproduce the issue. I appreciate you taking the time to post! I'll do what I can if you have any suggestions.

**Comment by patriksima** [comment]
```
{
  "name": "WrongWare",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "WrongWare s.r.o.",
  "license": "",
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-contrib-compass": "^1.0.1",
    "grunt-contrib-imagemin": "^0.9.2",
    "grunt-contrib-jshint": "^0.10.0",
    "grunt-contrib-sass": "^0.8.1",
    "grunt-contrib-uglify": "^0.9.1",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-jscodesniffer": "^0.1.10",
    "grunt-phpcs": "^0.4.0",
    "grunt-phplint": "0.0.5",
    "grunt-scss-lint": "^0.3.4",
    "imagemin-gifsicle": "^4.1.0",
    "imagemin-jpegtran": "^4.1.0",
    "imagemin-optipng": "^4.2.0",
    "imagemin-pngquant": "^4.1.0"
  },
  "dependencies": {
    "moment": "^2.9.0"
  }
}
```

**Comment by metaraine** [comment]
Works for me:

```
raine[ncu-sample-json]$ ncu

 grunt-contrib-jshint  ^0.10.0  →  ^0.11.3 
 grunt-contrib-sass     ^0.8.1  →   ^0.9.2 

The following dependencies are satisfied by their declared version range, but the installed versions are behind. You can install the latest versions without modifying your package file by using npm update. If you want to update the dependencies in your package file anyway, use --upgradeAll.

 moment                  ^2.9.0  →  ^2.10.6 
 grunt-contrib-compass   ^1.0.1  →   ^1.0.4 
 grunt-contrib-imagemin  ^0.9.2  →   ^0.9.4 
 grunt-contrib-uglify    ^0.9.1  →   ^0.9.2 
 grunt-scss-lint         ^0.3.4  →   ^0.3.8 
 imagemin-gifsicle       ^4.1.0  →   ^4.2.0 
 imagemin-jpegtran       ^4.1.0  →   ^4.3.1 
 imagemin-optipng        ^4.2.0  →   ^4.3.0 
 imagemin-pngquant       ^4.1.0  →   ^4.2.0 

raine[ncu-sample-json]$ npm -v
2.14.4
raine[ncu-sample-json]$ node -v
v4.1.2
raine[ncu-sample-json]$ 
```

**Comment by MatiasArriola** [comment]
I hit the same error today, and ended up here after googling it. As I had no much time to troubleshoot the issue, I just installed a randomly picked previous version doing `npm i -g npm-check-updates@2.2.0` and it worked just fine. 

In my initial attempt, when running `ncu`, I received the same `Cannot find module 'proto-list'` error. My operating system is Ubuntu 14.04, I use nvm and tried with both node 0.10.* and 4.2.*. 

I can debug the issue if I have some spare time the next couple of days.

**Comment by adam-lynch** [comment]
@MatiasArriola weird. I tried going back to `2.0.0` and it still failed.

**Comment by metaraine** [comment]
Hi @MatiasArriola. Thanks for reporting. If you have the opportunity to go into the source code and debug further, that would be a big help. So far we have just had people with time who can't reproduce, and people without time who can reproduce.

**Comment by MatiasArriola** [comment]
Hi, no problem. Hope I can contribute back in some way, though I'm not sure what's going on.

The error is not related to the package.json I am running ncu on, since running `ncu --version` also fails with the same error. 
As I mentioned before, I'm using nvm. I've just installed node v0.12.7, and `ncu` works fine there. Here is what I got by contrasting my new working vs non-working install:

Working:
```
node -v
v0.12.7
npm -v 
2.12.0
which ncu
/home/mati/.nvm/versions/node/v0.12.7/bin/ncu
```

Not working:
```
node -v
v4.2.1
npm -v
2.14.7
which ncu
/usr/local/bin/ncu
```

The problem: `npm-check-updates/node_modules/npm/node_modules/config-chain` requires the package `proto-list`.
There is no `node_modules` folder inside the `config-chain` package in any case.
The difference between both is that in the working install, `proto-list` is resolving to `npm-check-updates/node_modules/npm/node_modules/proto-list` (sibling of `config-chain`), while that module is not there in the broken setup (along many other missing packages).

After taking note of all this and before submitting this comment, I reinstalled node 4.2.1 and npm 2.14.7. Installed ncu, and it worked fine (all modules included in `npm-check-updates/node_modules/npm/node_modules/`). So I'm afraid I'm not able to reproduce the issue anymore. 

I am confused as to why all this happened, but I hope this information is helpful.

**Comment by metaraine** [comment]
Thank you for the additional information. I am as perplexed as you about the root cause. For now I will add a message on the README about this as a "known issue". If anyone else can consistently reproduce the problem *and* can find any indication that it is a bug in npm-check-updates, please let me know.

**Comment by metaraine** [comment]
The fact that it tries to find `proto-list` as a *sibling* of `config-chain` does imply that it has something to do with the new, flat hierarchy in npm v3. Maybe there is an issue when the installed npm is at v2 and the internal npm-check-updates' npm is at v3.
