### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by techelephant** [tjunnone/npm-check-updates#149]
When running "ncu -m bower" on a newly cloned repository, the following error occurs:

<em>Unhandled rejection TypeError: Cannot read property 'name' of undefined
    at /usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:252:31
    at Object.filterObject (/usr/local/lib/node_modules/npm-check-updates/node_modules/cint/cint.js:474:7)
    at /usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:251:34
    at tryCatcher (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:374:17)</em>

The error is thrown if ncu is run before executing bower install, i.e. without the existence of bower components according to the bower.json file.

Running "ncu -m npm" to update the package.json file, you don't need to run npm install first.

Version: npm-check-updates@2.3.0

<b>Workaround:</b> Clone a repository and run bower install. Then run the npm-check-updates to check bower dependencies and update the bower.json file. After updating the bower.json file run bower update.

**Comment by metaraine** [comment]
Thank you for reporting! Clearly a bug. I will investigate.

**Comment by metaraine** [comment]
Fixed in v2.3.1
