### ISSUE TITLE
Unhandled rejection Error: Error: Package not found

### ISSUE THREAD

**Issue by Davis22xd** [tjunnone/npm-check-updates#156]
I'm working on a Polymer project and I recently install ncu, I have all my dependencies in bower.json file, but when I run sudo ncu -m bower this happens:

Unhandled rejection Error: Error: Package paper-item not found
    at /usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:314:31
    at tryCatcher (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/util.js:26:23)
    at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/map.js:56:38)
    at MappingPromiseArray.init (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise_array.js:92:18)
    at MappingPromiseArray.init (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/map.js:29:23)
    at Async._drainQueue (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)

**Comment by metaraine** [comment]
Hi David, thanks for reporting! In general, please list the dependencies from your package file when reporting an issue.

It looks like you have a dependency in your bower.json file that does not exist on bower: `paper-item`

```
$ bower info paper-item
bower ENOTFOUND     Package paper-item not found
```

**Comment by Davis22xd** [comment]
Hi Raine, thanks, well my bower.json file is {
  "name": "sumitaxi",
  "version": "2.0.1",
  "authors": [
    "sumitrag-david <davisxdpfr@gmail.com>"
  ],
  "description": "Frontend Sumitaxi refactor",
  "license": "Copyright",
  "homepage": "booking.sumitrag.com",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "app/bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "polymer": "Polymer/polymer#^1.0.0",
    "paper-item": "PolymerElements/paper-item#^1.0.0",
    "paper-material": "PolymerElements/paper-material#^1.0.0",
    "paper-ripple": "PolymerElements/paper-ripple#^1.0.0",
    "iron-ajax": "PolymerElements/iron-ajax#1.0.0",
    "paper-icon-button": "PolymerElements/paper-icon-button#^1.0.0",
    "paper-dialog-behavior": "PolymerElements/paper-dialog-behavior#^1.0.0",
    "paper-dialog": "PolymerElements/paper-dialog#^1.0.0",
    "paper-input": "PolymerElements/paper-input#^1.0.0",
    "iron-collapse": "PolymerElements/iron-collapse#^1.0.0",
    "paper-dropdown-menu": "PolymerElements/paper-dropdown-menu#^1.0.0",
    "paper-button": "PolymerElements/paper-button#^1.0.0",
    "paper-card": "PolymerElements/paper-card#^1.0.0",
    "paper-date-picker": "~0.1.5",
    "polymer-paper-datepicker": "~1.0.3",
    "iron-form": "PolymerElements/iron-form#^1.0.0",
    "paper-checkbox": "PolymerElements/paper-checkbox#^1.0.0",
    "iron-a11y-keys": "PolymerElements/iron-a11y-keys#^1.0.0",
    "neon-animation": "PolymerElements/neon-animation#^1.0.0"
  }
}

In that case I have to search for another method to update all my dependencies?

**Comment by metaraine** [comment]
As of v2.3.4, npm-check-updates will ignore bower dependencies that are specified as github repos (`PolymerElements/paper-item#^1.0.0`) as it already does with npm.
