### ISSUE TITLE
TypeError: Cannot read property 'dist-tags.latest' of undefined

### ISSUE THREAD

**Issue by jcope2013** [tjunnone/npm-check-updates#162]
was working up until recently

npm-check-updates 2.3.4
node v0.12.7

``` 
ncu
Unhandled rejection Error: TypeError: Cannot read property 'dist-tags.latest' of undefined
    at /Users/joshuacope/.nvm/versions/node/v0.12.7/lib/node_modules/npm-check-updates/lib/versionmanager.js:316:31
    at tryCatcher (/Users/joshuacope/.nvm/versions/node/v0.12.7/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/util.js:26:23)
    at MappingPromiseArray._promiseFulfilled (/Users/joshuacope/.nvm/versions/node/v0.12.7/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/map.js:56:38)
    at MappingPromiseArray.init [as _init$] (/Users/joshuacope/.nvm/versions/node/v0.12.7/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/promise_array.js:92:18)
    at MappingPromiseArray.init (/Users/joshuacope/.nvm/versions/node/v0.12.7/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/map.js:29:23)
    at Async._drainQueue (/Users/joshuacope/.nvm/versions/node/v0.12.7/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/joshuacope/.nvm/versions/node/v0.12.7/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/joshuacope/.nvm/versions/node/v0.12.7/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by listepo** [comment]
+1

**Comment by metaraine** [comment]
Hi, thanks for reporting. Can you please include a list of your dependencies from your package.json?

**Comment by listepo** [comment]
```json
{
  "name": "web",
  "version": "1.0.0-alpha.1",
  "description": "Small description for web goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "Ivan Tugay",
  "license": "MIT",
  "devDependencies": {
    "babel-eslint": "4.1.3",
    "broccoli-asset-rev": "2.3.0",
    "ember-cli": "1.13.8",
    "ember-cli-app-version": "1.0.0",
    "ember-cli-babel": "5.1.5",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "1.1.0",
    "ember-cli-deploy": "0.5.0",
    "ember-cli-deploy-lightning-pack": "0.2.0",
    "ember-cli-htmlbars": "1.0.1",
    "ember-cli-htmlbars-inline-precompile": "0.3.1",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "1.3.1",
    "ember-cli-moment-shim": "0.6.2",
    "ember-cli-notifications": "2.1.2",
    "ember-cli-qunit": "1.0.3",
    "ember-cli-release": "0.2.8",
    "ember-cli-semantic-ui": "0.8.0",
    "ember-cli-simple-auth": "0.8.0",
    "ember-cli-simple-auth-token": "0.7.3",
    "ember-cli-sri": "1.1.0",
    "ember-cli-template-debug": "0.1.0",
    "ember-cli-uglify": "1.2.0",
    "ember-data": "1.13.8",
    "ember-disable-proxy-controllers": "1.0.1",
    "ember-export-application-global": "1.0.5",
    "ember-get-helper": "1.0.4",
    "ember-inputmask": "ROI4CIO/ember-inputmask",
    "ember-models-table": "1.3.6",
    "ember-moment": "4.1.0",
    "ember-page-title": "2.0.7",
    "ember-pikaday": "0.13.0",
    "ember-truth-helpers": "1.2.0",
    "ember-watson": "0.7.0",
    "eslint": "1.8.0"
  }
}

```

**Comment by listepo** [comment]
node: 0.12.7
npm: 2.13.4
ncu: 2.3.4

**Comment by metaraine** [comment]
The problem is with [ember-data](https://github.com/emberjs/data). It is published to the npm registry in such a way that `npm view ember-data` returns an empty response. I'm not sure how they managed that, since existing packages return a JSON object and non-existing packages return a 404.

I would suggest reporting to [ember-data issues](https://github.com/emberjs/data/issues).

**Comment by kevin-smets** [comment]
Hmmm, electron-prebuilt is suffering from this as well now... Would it be possible to report which package check threw an error? Just removed all lines one by one by hand, which is manageable with a small package.json :). But if it's rather big, it's not going to be pretty when trying to find the culprit.

**Comment by metaraine** [comment]
Is it erroring out? The [last commit](https://github.com/tjunnone/npm-check-updates/commit/0072ea348e3775edb01c9ddc527458d4e5c2edf7) should have made it so those packages just get ignored.

**Comment by kevin-smets** [comment]
Ah damn, my bad. Was checking with the global installed ncu instead of the local one, which appeared to be stuck on 2.2.0.. Updated and after that nothing but smooth sailing. Sorry!
