### ISSUE TITLE
Cannot find module 'npm-registry-client'

### ISSUE THREAD

**Issue by robertbaker** [tjunnone/npm-check-updates#168]
```

module.js:339
    throw err;
    ^

Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\rbaker\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\lib\cache\caching-client.js:9:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at C:\Users\rbaker\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\lib\npm.js:28:26
    at Object.<anonymous> (C:\Users\rbaker\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\lib\npm.js:485:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)


```

This is because of the NPM version in the dependency list. 3.4.1 is out and works fine. Then again, do we need a copy of NPM as a dependency when you need and have NPM already?

**Comment by metaraine** [comment]
Hi, thanks for reporting.

> This is because of the NPM version in the dependency list.

Can you explain this more? I would like to understand better what's causing the problem.

**Comment by robertbaker** [comment]
NPM is listed as a dependency, the version obtained has an issue that causes this error.

It may be fixed by using NPM 3.3.12, or NPM@3.4.1

**Comment by metaraine** [comment]
Thanks, I'll bump the non dependency version then.

**Comment by glen-84** [comment]
I have the same problem.

```
$ node -v
v5.1.0

$ npm -v
3.4.1
```

```
$ npm list -g --depth=0
C:\Users\Glen\AppData\Roaming\npm
├── gulp@3.9.0
├── jspm@0.16.14
├── live-server@0.8.2
├── npm-check-updates@2.5.1
├── tsd@0.6.5
└── tslint@2.5.1

npm ERR! error in C:\Users\Glen\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\node_modules\npm-registry-client: ENOENT: no such file or directory, open 'C:\Users\Glen\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\node_modules\npm-registry-client\package.json'
npm ERR! invalid: npm-registry-client C:\Users\Glen\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\node_modules\npm-registry-client
npm ERR! extraneous: npmlog@2.0.0 C:\Users\Glen\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog
npm ERR! error in C:\Users\Glen\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npmi\node_modules\npm\node_modules\npm-registry-client: ENOENT: no such file or directory, open 'C:\Users\Glen\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npmi\node_modules\npm\node_modules\npm-registry-client\package.json'
npm ERR! invalid: npm-registry-client C:\Users\Glen\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npmi\node_modules\npm\node_modules\npm-registry-client
npm ERR! extraneous: npmlog@2.0.0 C:\Users\Glen\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npmi\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog
```

**Comment by robertbaker** [comment]
@glen-84 try npm@3.5

**Comment by glen-84** [comment]
@robertbaker Thanks, that works.

**Comment by screendriver** [comment]
Same here. [npmjs.com](https://www.npmjs.com/package/npm) tells me that the latest release of `npm` is 3.4.1. Where can I find 3.5?

**Comment by glen-84** [comment]
@screendriver I think I did `npm install npm@3.5.0`.

**Comment by niemyjski** [comment]
+1

**Comment by luisrudge** [comment]
Upgrading to 3.5.0 didn't work for me.

**Comment by niemyjski** [comment]
Same here (OS X running latest everything)

**Comment by metaraine** [comment]
Does the error occur if you pipe your package.json to ncu? This will tell me if using `npm.commands.list` from the dependency instead of from the local npm is causing the problem.

```
cat package.json | ncu
```

**Comment by niemyjski** [comment]
I can't even install ncu...

```bash
blake@:~$ npm install -g npm-check-updates
/Users/blake/.npm-packages/lib
└── (empty)

npm WARN In npm-check-updates@2.5.1 replacing bundled version of chalk with chalk@1.1.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of async with async@1.5.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of get-stdin with get-stdin@5.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of semver-utils with semver-utils@1.1.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of require-dir with require-dir@0.3.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of find-up with find-up@1.1.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of json-parse-helpfulerror with json-parse-helpfulerror@1.0.3
npm WARN In npm-check-updates@2.5.1 replacing bundled version of cli-table with cli-table@0.3.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of semver with semver@5.1.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of fast-diff with fast-diff@1.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of semver with semver@4.3.6
npm WARN In npm-check-updates@2.5.1 replacing bundled version of npmlog with npmlog@2.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of bluebird with bluebird@3.0.5
npm WARN In npm-check-updates@2.5.1 replacing bundled version of cint with cint@8.2.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of lodash with lodash@3.10.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of update-notifier with update-notifier@0.5.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of commander with commander@2.9.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of supports-color with supports-color@2.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of ansi-styles with ansi-styles@2.1.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of strip-ansi with strip-ansi@3.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of escape-string-regexp with escape-string-regexp@1.0.3
npm WARN In npm-check-updates@2.5.1 replacing bundled version of has-ansi with has-ansi@2.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of ansi-regex with ansi-regex@2.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of colors with colors@1.0.3
npm WARN In npm-check-updates@2.5.1 replacing bundled version of graceful-readlink with graceful-readlink@1.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of path-exists with path-exists@2.1.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of pinkie-promise with pinkie-promise@2.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of pinkie with pinkie@2.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of jju with jju@1.2.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of are-we-there-yet with are-we-there-yet@1.0.4
npm WARN In npm-check-updates@2.5.1 replacing bundled version of gauge with gauge@1.2.2
npm WARN In npm-check-updates@2.5.1 replacing bundled version of readable-stream with readable-stream@1.1.13
npm WARN In npm-check-updates@2.5.1 replacing bundled version of delegates with delegates@0.1.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of core-util-is with core-util-is@1.0.2
npm WARN In npm-check-updates@2.5.1 replacing bundled version of isarray with isarray@0.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of inherits with inherits@2.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of string_decoder with string_decoder@0.10.31
npm WARN In npm-check-updates@2.5.1 replacing bundled version of ansi with ansi@0.3.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of has-unicode with has-unicode@1.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of lodash.padleft with lodash.padleft@3.1.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of lodash.pad with lodash.pad@3.1.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of lodash.padright with lodash.padright@3.1.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of lodash._basetostring with lodash._basetostring@3.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of lodash._createpadding with lodash._createpadding@3.6.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of lodash.repeat with lodash.repeat@3.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of configstore with configstore@1.3.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of is-npm with is-npm@1.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of semver-diff with semver-diff@2.1.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of latest-version with latest-version@1.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of string-length with string-length@1.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of repeating with repeating@1.1.3
npm WARN In npm-check-updates@2.5.1 replacing bundled version of uuid with uuid@2.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of os-tmpdir with os-tmpdir@1.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of write-file-atomic with write-file-atomic@1.1.3
npm WARN In npm-check-updates@2.5.1 replacing bundled version of object-assign with object-assign@4.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of xdg-basedir with xdg-basedir@2.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of mkdirp with mkdirp@0.5.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of graceful-fs with graceful-fs@4.1.2
npm WARN In npm-check-updates@2.5.1 replacing bundled version of osenv with osenv@0.1.3
npm WARN In npm-check-updates@2.5.1 replacing bundled version of minimist with minimist@0.0.8
npm WARN In npm-check-updates@2.5.1 replacing bundled version of os-homedir with os-homedir@1.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of slide with slide@1.1.6
npm WARN In npm-check-updates@2.5.1 replacing bundled version of package-json with package-json@1.2.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of registry-url with registry-url@3.0.3
npm WARN In npm-check-updates@2.5.1 replacing bundled version of object-assign with object-assign@3.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of readable-stream with readable-stream@2.0.4
npm WARN In npm-check-updates@2.5.1 replacing bundled version of readable-stream with readable-stream@2.0.4
npm WARN In npm-check-updates@2.5.1 replacing bundled version of pinkie-promise with pinkie-promise@1.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of pinkie with pinkie@1.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of nested-error-stacks with nested-error-stacks@1.0.2
npm WARN In npm-check-updates@2.5.1 replacing bundled version of prepend-http with prepend-http@1.0.3
npm WARN In npm-check-updates@2.5.1 replacing bundled version of lowercase-keys with lowercase-keys@1.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of is-stream with is-stream@1.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of infinity-agent with infinity-agent@2.0.3
npm WARN In npm-check-updates@2.5.1 replacing bundled version of timed-out with timed-out@2.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of is-redirect with is-redirect@1.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of end-of-stream with end-of-stream@1.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of once with once@1.3.3
npm WARN In npm-check-updates@2.5.1 replacing bundled version of wrappy with wrappy@1.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of util-deprecate with util-deprecate@1.0.2
npm WARN In npm-check-updates@2.5.1 replacing bundled version of process-nextick-args with process-nextick-args@1.0.3
npm WARN In npm-check-updates@2.5.1 replacing bundled version of minimist with minimist@1.2.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of ini with ini@1.3.4
npm WARN In npm-check-updates@2.5.1 replacing bundled version of strip-json-comments with strip-json-comments@1.0.4
npm WARN In npm-check-updates@2.5.1 replacing bundled version of deep-extend with deep-extend@0.4.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of is-finite with is-finite@1.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of number-is-nan with number-is-nan@1.0.0
npm WARN In npm-check-updates@2.5.1 replacing bundled version of got with got@3.3.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of duplexify with duplexify@3.4.2
npm WARN In npm-check-updates@2.5.1 replacing bundled version of read-all-stream with read-all-stream@3.0.1
npm WARN In npm-check-updates@2.5.1 replacing bundled version of rc with rc@1.1.5
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.1.0/bin/node" "/Users/blake/.npm-packages/bin/npm" "install" "-g" "npm-check-updates"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.0
npm ERR! path /Users/blake/.npm-packages/lib/node_modules/.staging/core-util-is-c2666d0a53bd67f5184e6edb2f235851
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/blake/.npm-packages/lib/node_modules/.staging/core-util-is-c2666d0a53bd67f5184e6edb2f235851' -> '/Users/blake/.npm-packages/lib/node_modules/npm-check-updates/node_modules/npmi/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/node_modules/core-util-is'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/blake/.npm-packages/lib/node_modules/.staging/core-util-is-c2666d0a53bd67f5184e6edb2f235851' -> '/Users/blake/.npm-packages/lib/node_modules/npm-check-updates/node_modules/npmi/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/node_modules/core-util-is'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/blake/npm-debug.log
npm ERR! code 1
```

**Comment by metaraine** [comment]
@niemyjski That's a new one. Please create a new issue and we'll track that.

For others still having a "cannot find module" error, let me know if `cat package.json | ncu` gives the error as well, otherwise I'll need some assistance troubleshooting, as I cannot reproduce the error myself.

**Comment by niemyjski** [comment]
blake@:~$ cat package.json
cat: package.json: No such file or directory

**Comment by niemyjski** [comment]
Could we just join a team viewer session?

**Comment by metaraine** [comment]
(If you don't have a local package.json, replace the `cat` test with something like `echo "{ \"dependencies\": { \"chalk\": \"1.0.0\" } }" | ncu`).

@niemyjski Can't do a team viewer session right now. I am curious about the install error, as I have not seen that before. What would cause it not to install correctly? npm says the error "is related to npm not being able to find a file" which would suggest to me some kind of permission issue, not an error with npm-check-updates itself. I would still suggest opening a separate issue, as this issue (#168) is specifically for the "cannot find module" error.

**Comment by niemyjski** [comment]
```
echo "{ \"dependencies\": { \"chalk\": \"1.0.0\" } }" | ncu
module.js:340
    throw err;
    ^

Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/blake/.npm-packages/lib/node_modules/npm-check-updates/node_modules/npmi/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/blake/.npm-packages/lib/node_modules/npm-check-updates/node_modules/npmi/node_modules/npm/lib/npm.js:23:24
    at Object.<anonymous> (/Users/blake/.npm-packages/lib/node_modules/npm-check-updates/node_modules/npmi/node_modules/npm/lib/npm.js:469:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
```

**Comment by niemyjski** [comment]
https://github.com/npm/npm/issues/2528 ?

**Comment by metaraine** [comment]
Indeed. I wonder if it has something to do with npmi using npm v2 while npm-check-updates uses v3? I'm  kind of stumped :/.

**Comment by glen-84** [comment]
@niemyjski Which version of NPM are you using?

**Comment by niemyjski** [comment]
3.5.0

**Comment by metaraine** [comment]
It's really confusing when there are potentially 3 versions of npm floating around: the installed, npm-check-update's, and npmi's...

**Comment by glen-84** [comment]
@niemyjski I would start by updating to 3.5.1, and if that doesn't help, follow the last comment in the issue that you linked to.

**Comment by niemyjski** [comment]
I just reinstalled everything node, npm and it works now.. It pulled down 3.5.0 and nacu says everything is up to date.

**Comment by metaraine** [comment]
Glad there was a solution. Not glad that people are running into this to begin with! Frustrating.

**Comment by raineorshine** [comment]
ncu now uses the system npm, so this shouldn't be an issue any longer.
