### ISSUE TITLE
ncu behing coporate proxy

### ISSUE THREAD

**Issue by Toilal** [tjunnone/npm-check-updates#169]
I'm behind a coporate proxy and most command line tools from nodeJS ecosystem works with ```HTTP_PROXY``` and ```HTTPS_PROXY``` environment defined.

Sadly, ```ncu -m bower``` doesn't work in this environment.

```
ncu -m bower
Unhandled rejection Error: Failed to execute "git ls-remote --tags --heads https://github.com/nervgh/angular-file-upload.git", exit code of #128
fatal: unable to access 'https://github.com/nervgh/angular-file-upload.git/': Could not resolve proxy: undefined

    at createError (/home/ralvergnat/.npm-packages/lib/node_modules/npm-check-updates/node_modules/bower/lib/util/createError.js:4:15)
    at ChildProcess.<anonymous> (/home/ralvergnat/.npm-packages/lib/node_modules/npm-check-updates/node_modules/bower/lib/util/cmd.js:102:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

But standalone git command just works as expected.

```
$ git ls-remote --tags --heads https://github.com/nervgh/angular-file-upload.git
f1310b2dd40384f49b88842a10d6f670f6841d4c	refs/heads/master
21d4ecd31ab9c435552837684ee364e940ad68a4	refs/heads/version-3.0.0-alpha
db38b616300db82abeb85e78eff6961e2949a2a9	refs/tags/v0.2.1
27b9403c6aa5cd3b4652cb91dc76a68a9f2036cc	refs/tags/v0.2.4
68cea03fea15e8b04d276dd30c373196ba732fa1	refs/tags/v0.2.5
c55873846a14a9b7487c3dab83afcd5c7acc10f7	refs/tags/v0.2.7
fd0aac4711bc332e2be5b8e9901d754b3666d187	refs/tags/v0.2.8.1
60edbc614c493878740af804c60315074d3b913b	refs/tags/v0.2.8.4
10199487c4b3df2a924fe07f34a7d519c3bd2cda	refs/tags/v0.2.8.6
2a4a26d503f34179e44189695c3b00d31ec33c56	refs/tags/v0.2.8.7
529efef90f39f2f0539f1237d32e36d8eb7f9a96	refs/tags/v0.2.8.8
103d68324c6c209d60da23fe219d9ba19c121807	refs/tags/v0.2.8.9
55609ba724980dfc2b70f35a09eb3a3ceea7ff7a	refs/tags/v0.2.9.4
f26fd02868fcfcc4cca55c625b013a17663549bf	refs/tags/v0.2.9.6
a339cae018a0b4a8712092461924e154f1c91d9f	refs/tags/v0.3
a17a66d8c4b804eccc9133486b1e62e6399e59c2	refs/tags/v0.3.1
be0f71f319ada77a3ee34ed192ebca299ca7a8f1	refs/tags/v0.3.1^{}
44d54ea50758a9156cec5cb66a6e8f192c7d7298	refs/tags/v0.3.3.1
01a29430cb83c395b9b460f2b4d07ef832774171	refs/tags/v0.4.0
21a992a3b6cd15fcc4aa6d7b0ea2cfc72c0974cd	refs/tags/v0.4.1
a4217d10b393ec596ad8079bc926a160fc85d868	refs/tags/v0.5.4
468fca03d303c1db3bd9a4bef6005c214bad3142	refs/tags/v0.5.5
34008ab7d5753d12412e591c00e380317e543a6b	refs/tags/v0.5.6
da8c0774c0577bca546dc49c08b240c74517029e	refs/tags/v0.5.7
bf17da4b4f9f1a74d410cd351bf3d7da128f1f47	refs/tags/v1.0.1
c3d0fbff36118d78a8483d25413101d17ff837f7	refs/tags/v1.0.2
5c18aeca81f56b5fe6d3a79bc267e4a13f258488	refs/tags/v1.0.3
1ee0dba97cc26734ae09f9d62fa4819ed1a4ad27	refs/tags/v1.1.0
c76bc05d2b3363606c09976ae28ceb3ddeb38116	refs/tags/v1.1.1
01c3c75bb4a308cc552a9453fc0c23dbdde44ba6	refs/tags/v1.1.4
6c832bbdd0e5b084848ad4246c1e7b44dc2a532f	refs/tags/v1.1.5
1bf43e92ecb1bd46ffe34bbcd10d6173012b1b1d	refs/tags/v1.1.6
5100d9676ed3af410009b1a020d55f84a9a0a73e	refs/tags/v2.0.0
691bdc50f214cb04901d356e71118990c805ac99	refs/tags/v2.0.1
51cc05a28b875202f28551e4de8ee279846f6673	refs/tags/v2.1.0
d744768da615ab7269935efceb1227473c08ec23	refs/tags/v2.1.1
dd0fd26b385ab5bae4fccf249b62e9544a022bfe	refs/tags/v2.1.2
1d66c4c450b95fefe6f4e20615c508f61656023f	refs/tags/v2.1.3
888127c60b2946196784a3af474931ae48a8afca	refs/tags/v2.1.4
f8c81dfa1eb6334a374ad3e976715492ab602dbc	refs/tags/v2.2.0
151a3a1575f473d90e973fc49ca764529fb38fea	refs/tags/v_0.1
14ba5f22438eeb10d962105d38bba908356ae869	refs/tags/v_0.2
```

**Comment by Toilal** [comment]
Maybe it's related to this issue : https://github.com/bower/bower/issues/1426

**Comment by Toilal** [comment]
Workaround is to define proxy in git configuration with the following commands:

```
git config --global http.proxy http://proxy...
git config --global https.proxy https://proxy...
```

I close this issue because I think it's definitevely related to the bower issue mentioned in previous message.

**Comment by metaraine** [comment]
Thanks!
