### ISSUE TITLE
Warnings when used

### ISSUE THREAD

**Issue by devinus** [tjunnone/npm-check-updates#174]
Getting these two warnings:

```
Warning: .settle() is deprecated and will be removed in a future version. Use .reflect() instead.
    at Object.getLatestVersions (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/lib/versionmanager.js:306:20)
    at upgradePackageDefinitions (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:107:15)
    at analyzeProjectDependencies (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:162:9)
    at wrapper (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:3533:19)
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
From previous event:
    at programRunLocal (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:380:20)
    at programRun (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:322:50)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
From previous event:
    at Object.module.exports._.merge.run (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:403:12)
    at Object.<anonymous> (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/bin/npm-check-updates:38:5)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

```
Warning: a promise was created in a  handler but was not returned from it
    at /Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:195:21
From previous event:
    at analyzeProjectDependencies (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:164:6)
    at wrapper (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:3533:19)
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
From previous event:
    at programRunLocal (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:380:20)
    at programRun (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:322:50)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
From previous event:
    at Object.module.exports._.merge.run (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:403:12)
    at Object.<anonymous> (/Users/devinus/.anyenv/envs/ndenv/versions/v5.0.0/lib/node_modules/npm-check-updates/bin/npm-check-updates:38:5)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by tshani** [comment]
Same warning here.

**Comment by stickystyle** [comment]
I get the same messages checking local and global packages, at the bottom it tells me all packages are up to date when I know that to be false.

**Comment by metaraine** [comment]
Thanks! I am not seeing that warning, but regardless settle will be removed as soon as the [progress-bar](https://github.com/tjunnone/npm-check-updates/tree/progress-bar) feature branch gets merged.

@stickystyle That sounds like a different issues, "ncu -g doesn't work" (#146).
