### ISSUE TITLE
2.5.4 broken

### ISSUE THREAD

**Issue by niieani** [tjunnone/npm-check-updates#184]
Any invocation of `ncu` results in this error:
```
module.js:340
    throw err;
    ^

Error: Cannot find module 'config-chain'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/config/core.js:1:72)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/npm.js:22:17
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/npm.js:485:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
```

**Comment by niieani** [comment]
Reinstallation helped.
