### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by codemonkey800** [tjunnone/npm-check-updates#202]
I just upgraded my Node to v5.5.0 and my npm to v3.7.0 through nvm. When running 
```bash
npm -g install npm-check-updates
```
I get the following error:
```bash
npm ERR! node v5.5.0
npm ERR! npm  v3.7.0

npm ERR! Converting circular structure to JSON
```

Anybody know a possible workaround or maybe a possible fix for this?

**Comment by metaraine** [comment]
The install went fine for me, so I unfortunately can't reproduce :/.

**Comment by codemonkey800** [comment]
Well this sucks :sob: 

If it helps, I ran the command using verbose loglevel and got this:

```
npm verb stack TypeError: Converting circular structure to JSON
npm verb stack     at Object.stringify (native)
npm verb stack     at clone (/home/jeremy/.nvm/versions/node/v5.5.0/lib/node_modules/npm/lib/fetch-package-metadata.js:30:26)
npm verb stack     at /home/jeremy/.nvm/versions/node/v5.5.0/lib/node_modules/npm/lib/fetch-package-metadata.js:112:39
npm verb stack     at /home/jeremy/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm verb stack     at mapToRegistry (/home/jeremy/.nvm/versions/node/v5.5.0/lib/node_modules/npm/lib/utils/map-to-registry.js:55:3)
npm verb stack     at fetchNamedPackageData (/home/jeremy/.nvm/versions/node/v5.5.0/lib/node_modules/npm/lib/fetch-package-metadata.js:110:3)
npm verb stack     at fetchPackageMetadata (/home/jeremy/.nvm/versions/node/v5.5.0/lib/node_modules/npm/lib/fetch-package-metadata.js:62:5)
npm verb stack     at resolveWithNewModule (/home/jeremy/.nvm/versions/node/v5.5.0/lib/node_modules/npm/lib/install/deps.js:455:12)
npm verb stack     at /home/jeremy/.nvm/versions/node/v5.5.0/lib/node_modules/npm/lib/install/deps.js:397:7
npm verb stack     at /home/jeremy/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
```

**Comment by 4kochi** [comment]
This is a bug in npm itself https://github.com/npm/npm/issues/11349
