### ISSUE TITLE
ncu fails when original github repository no longer exists

### ISSUE THREAD

**Issue by jrencz** [tjunnone/npm-check-updates#226]
1: add:

```json
{
  "dependencies": {
    "ngTouchSpin": "JulienDeray/ngTouchSpin"
  }
}
```

2: run `ncu -m bower`

Observe error:

```
Unhandled rejection Error: Failed to execute "git ls-remote --tags --heads https://github.com/jkuri/ngTouchSpin.git", exit code of #128
remote: Repository not found.
fatal: repository 'https://github.com/jkuri/ngTouchSpin.git/' not found

    at createError (/Users/jrencz/.nvm/versions/node/v4.2.1/lib/node_modules/bower/lib/util/createError.js:4:15)
    at ChildProcess.<anonymous> (/Users/jrencz/.nvm/versions/node/v4.2.1/lib/node_modules/bower/lib/util/cmd.js:102:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
``` 

`jkuri/ngTouchSpin` is where package published as `ngTouchSpin` was, but the author decided to remove the repository (or transfer ownership?).

I suggest `ncu` should try `JulienDeray/ngTouchSpin` in such case

**Comment by metaraine** [comment]
Hi, thanks for reporting! ncu does not currently support direct GitHub repo
references. You will have to reference a project that has been published to
npm or bower.

The error should be caught however and something more informative provided
to the user when this happens.

Others have requested support for GitHub urls, so this could be a good
opportunity for someone to submit a pull request. I do not have additional
availability at the moment.

**Comment by raineorshine** [comment]
Closing for cleanup purposes and adding the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=label%3Arevive-me) label. Feel free to re-open if you are interested in working on a pull request.
