### ISSUE TITLE
Bower fails on invalid version numbers (TypeError: Invalid Version)

### ISSUE THREAD

**Issue by tjama** [tjunnone/npm-check-updates#246]
ncu version 2.6.7 on Windows 7, node v6.2.2

```
C:\DEV>ncu -m bower
Unhandled rejection TypeError: Invalid Version: 2.2-jsdw
    at new SemVer (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\node_modules\semver\semver.js:273:11)
    at compare (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\node_modules\semver\semver.js:460:10)
    at Object.neq (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\node_modules\semver\semver.js:504:10)
    at GitHubResolver.GitResolver._savePkgMeta (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers
\GitResolver.js:209:56)
    at GitHubResolver._savePkgMeta (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers\GitHubResol
ver.js:134:53)
    at _fulfilled (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:79
6:13)
    at C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:604:44
    at runSingle (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:137:13)
    at flush (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by raineorshine** [comment]
It appears that one of your dependencies is using a version number that is
not valid semver: 2.2-jsdw. npm-check-updates only works for packages that
use valid semver versions. It's unfortunate that the error does not reveal
the name of the transgressing package, but you can find that by removing
dependencies one by one until the error goes away. I suggest contacting the
package author or making a pull request to request a valid semver version.

**Comment by GvS666** [comment]
I've made a PR in bower to fix this issue: https://github.com/bower/bower/pull/2316

**Comment by raineorshine** [comment]
Great!
