### ISSUE TITLE
Error: "Path must be a string. Received undefined" v2.8.1

### ISSUE THREAD

**Issue by elado** [tjunnone/npm-check-updates#277]
Node 6.7.0
Just installed npm-check-updates 2.8.1 globally.
Getting this error on any `ncu` command.

```
$ ncu
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at Conf.loadPrefix (~/.nvm/versions/node/v6.7.0/lib/node_modules/npm-check-updates/node_modules/npm/lib/config/load-prefix.js:43:14)
    at load_ (~/.nvm/versions/node/v6.7.0/lib/node_modules/npm-check-updates/node_modules/npm/lib/config/core.js:109:8)
    at Conf.<anonymous> (~/.nvm/versions/node/v6.7.0/lib/node_modules/npm-check-updates/node_modules/npm/lib/config/core.js:96:5)
    at emitOne (events.js:96:13)
    at Conf.emit (events.js:188:7)
    at ConfigChain._resolve (~/.nvm/versions/node/v6.7.0/lib/node_modules/npm-check-updates/node_modules/npm/node_modules/config-chain/index.js:281:34)
    at ConfigChain.add (~/.nvm/versions/node/v6.7.0/lib/node_modules/npm-check-updates/node_modules/npm/node_modules/config-chain/index.js:259:10)
    at Conf.add (~/.nvm/versions/node/v6.7.0/lib/node_modules/npm-check-updates/node_modules/npm/lib/config/core.js:341:27)
    at Conf.<anonymous> (~/.nvm/versions/node/v6.7.0/lib/node_modules/npm-check-updates/node_modules/npm/lib/config/core.js:320:25)
    at ReadFileContext.callback (~/.nvm/versions/node/v6.7.0/lib/node_modules/npm-check-updates/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
```

This error is only in 2.8.1. Reverted to 2.8.0 and it works.

```
npm install -g npm-check-updates@2.8.0
```

**Comment by dbackowski** [comment]
Node 6.3.0 same error.

**Comment by fgaeg** [comment]
Same here

```
node -v
v6.5.0
npm -v
3.10.8
```

**Comment by cajoy** [comment]
+1

**Comment by raineorshine** [comment]
Thanks for reporting. I am a little stumped considering all tests are passing, even on Travis. Is that the whole stack trace? I can't make out the actual file in npm-check-updates that is triggering the error.

**Comment by raineorshine** [comment]
Looks similar to [some other issues](https://github.com/TypeStrong/ts-loader/issues/246#issuecomment-243090933) where `path.dirname` handles undefined differently in node 6.x. Just speculation though.

> The problem is with path.dirname. In node 5.x, path.dirname(undefined) returns '.', whereas in node 6.x it returns undefined. That's why an exceptions gets thrown in node 6.x if you're using tsloader without a tsconfig.json file.

When I switch to node v6 however I still don't get the error. Maybe someone who is able to reproduce can test node v5 and node v6 to see if this might be the issues.

**Comment by raineorshine** [comment]
I installed npm-check-updates@2.8.1 on a fresh install of node v6.1.0 using nvm and I am able to reproduce it, so hopefully can do some profitable troubleshooting now.

`path` is only used in one place, so I'm going to try messing with it:
https://github.com/tjunnone/npm-check-updates/blob/cfc1a2a8b42ff8759e910f8498a35fedd1e6048e/lib/npm-check-updates.js#L378

**Comment by raineorshine** [comment]
I think I found it. Has to do with the lodash upgrade and changed merge behavior.

**Comment by raineorshine** [comment]
Try now! `v2.8.2`

**Comment by cajoy** [comment]
Fixed for me

**Comment by fgaeg** [comment]
Aah. Works fine now. Gracias!
