### ISSUE TITLE
ncu command complains of missing lodash library thought it is installed

### ISSUE THREAD

**Issue by super-iterator** [tjunnone/npm-check-updates#307]
When issuing the command `ncu` like below

>  $$ ncu

The package throws errors of uninstalled `lodash` package, though it is installed in globally and in the project scope. What can be the problem?

Using /Users/admin/Desktop/testSails/apier/package.json
```

/usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/install/deps.js:130
        tree.missingDeps[req.name] = req.rawSpec
                                   ^

TypeError: Cannot set property 'lodash' of undefined
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/install/deps.js:130:36
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/install/deps.js:107:5
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/npm/node_modules/dezalgo/dezalgo.js:17:12
    at RawTask.call (/usr/local/lib/node_modules/npm-check-updates/node_modules/npm/node_modules/asap/asap.js:40:19)
    at flush (/usr/local/lib/node_modules/npm-check-updates/node_modules/npm/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by raineorshine** [comment]
`lodash` is given correctly as a dependency, so something must have gone wrong in the installation. Could you try uninstalling and then re-installing npm-check-updates? If that doesn't work, you may want to consider re-installing npm.

**Comment by super-iterator** [comment]
@raineorshine, that was it :)

**Comment by super-iterator** [comment]
Solved

**Comment by raineorshine** [comment]
Great!
