### ISSUE TITLE
TypeError: require.extensions.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by jessehattabaugh** [tjunnone/npm-check-updates#367]
* node version: 8.1.1
* npm version: 5.0.3
* npm-check-updates version: 2.11.3

---------------------------

I get the following error when running `ncu`

```
Jesses-MacBook-Pro:frontend jesse$ ncu
/usr/local/lib/node_modules/npm-check-updates/node_modules/require-dir/index.js:97
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/usr/local/lib/node_modules/npm-check-updates/node_modules/require-dir/index.js:97:37)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:8:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:16:10)
```

Looks like it's coming from `require-dir`, but I didn't see any mention of it in their github issues either.

**Comment by raineorshine** [comment]
This issue has been solved. Please see this comment: https://github.com/tjunnone/npm-check-updates/issues/363#issuecomment-308452577

**Comment by jessehattabaugh** [comment]
Sorry, I swear I searched for this issue. Maybe I forgot to search for "closed" issues.

**Comment by raineorshine** [comment]
No problem! It was nice of you to take the time to report.

**Comment by khuongphp** [comment]
I have this error when use command `gulp` in laravel. So when i reinstall gulp in global, it 's resolved :D
`npm install -g gulp`

**Comment by meddjelaili** [comment]
I suggest you use nvm to install multiple node versions on your machine
Mac/Linux: https://github.com/creationix/nvm
Windows: https://github.com/coreybutler/nvm-windows
and use node v 6 for that project

**Comment by faisalraza** [comment]
I installed nvm (Node Version Manager) and downgraded node version from 8.8.1 to stable 6.11.0 and it resolved the issue.

nvm install 6.11.0

**Comment by rameshv1210** [comment]
Hello All 
I have this error when use command gulp in Phinx

**Comment by AndersDJohnson** [comment]
I'm still seeing this issue:
```
require.extensions.hasOwnProperty is not a function
```
when running command:
```
npx npm-check-updates
```
with `npx@6.14.2` and `node@12.3.1`.

**Comment by raineorshine** [comment]
@AndersDJohnson What's the full stack trace and file where the error occurs please?

**Comment by AndersDJohnson** [comment]
@raineorshine not sure, there doesn't appear to be a stack trace, it only outputs that one line of the error.

**Comment by raineorshine** [comment]
Darn. Was hoping to confirm if it was an old `require-dir` dependency that is causing it. `npm-check-updates` does not use `require-dir` any more. In all likelihood it's an issue with your npm install.s

**Comment by simondiep** [comment]
I'm running into the same issue.  Fresh project.

```
$ npx npm-check-updates -u
[INFO]: You can also use ncu as an alias
require.extensions.hasOwnProperty is not a function
$ node --version
v12.18.0
$ npm --version
6.14.4
```

**Comment by mrami4** [comment]
I'm currently seeing it as well. I happen to have a stack trace:

`[INFO]: You can also use ncu as an alias
/usr/local/lib/node_modules/npm-check-updates/node_modules/require-dir/index.js:97
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/usr/local/lib/node_modules/npm-check-updates/node_modules/require-dir/index.js:97:37)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:8:23)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:16:10)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/bin/ncu:6:11)
`

Node v14.6.0
npm-check-updates@7.0.2

**Comment by raineorshine** [comment]
Note that `require-dir` is **no longer a dependency** of `npm-check-updates`. If you are seeing this error, you are surely running an old version, perhaps because it is installed in more than one place.

Try running `/usr/local/lib/node_modules/npm-check-updates/bin/npm-check-updates --version` to check the version.

**Comment by mrami4** [comment]
Yes, indeed, it was stale.  Thank you!
