### ISSUE TITLE
Unhandled rejection TypeError: Invalid Version: modified

### ISSUE THREAD

**Issue by drcmda** [tjunnone/npm-check-updates#400]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v8.7.0
* npm version: 5.4.2
* npm-check-updates version: 2.13.0

---------------------------

Getting newest updates crashes ncu in one of my projects. All other variants run (latest by time, etc).

```
❯ npm-check-updates -n
[INFO]: You can also use ncu as an alias
Using package.json
Unhandled rejection TypeError: Invalid Version: modified
    at new SemVer (/usr/local/lib/node_modules/npm-check-updates/node_modules/semver/semver.js:293:11)
    at Range.test (/usr/local/lib/node_modules/npm-check-updates/node_modules/semver/semver.js:1100:15)
    at satisfies (/usr/local/lib/node_modules/npm-check-updates/node_modules/semver/semver.js:1149:16)
    at isUpgradeable (/usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:165:10)
    at apply (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:496:27)
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:10863:16
    at apply (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:495:27)
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:6600:16
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:13568:16
    at basePickBy (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:3781:13)
    at Function.pickBy (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:13567:14)
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:4379:28
    at arrayReduce (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:704:21)
    at baseWrapperValue (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:4378:14)
    at LodashWrapper.wrapperValue (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:9067:14)
    at upgradeDependencies (/usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:141:10)
```

**Comment by drcmda** [comment]
I went into node_modules to debug it, it chokes on the following package:

```
{ maintainers: [ 'mkeller <marcel.keller@awv-informatik.ch>' ],
  'dist-tags': { latest: '7.0.0' },
  versions: [ '7.0.0' ],
  name: '@awv/classcad_isoassemblybuilder_data',
  description: 'internal data package to run examples',
  time: 
   { created: '2017-04-20T14:02:04.001Z',
     '7.0.0': '2017-04-20T14:02:04.001Z',
     modified: '2017-04-20T14:02:04.001Z' },
  version: '7.0.0',
  scripts: { test: '' },
  keywords: [ 'awv' ],
  author: 'AWV Informatik AG <marcel.keller@awv-informatik.ch>',
  readme: 'ERROR: No README data found!',
  dist: 
   { shasum: 'cfaa47adfd3fb66b61a89b02a752411762e797be',
     tarball: 'https://nexus001.ntb.ch/repository/awv-npm-group/@awv/classcad_isoassemblybuilder_data/-/classcad_isoassemblybuilder_data-7.0.0.tgz' } }
```

**Comment by raineorshine** [comment]
Thanks for reporting! Could you provide the package that it fails on? It still works for me on a basic repo so it must be a specific package. That would help me be able to reproduce the issue. Thanks!

**Comment by brokenmass** [comment]
I just had the same issue running `ncu --newest` and identified the root cause. 
if a dependency has ONLY one published version, the time object of looks like this: 
```
time:
   { created: '2018-02-16T14:45:21.902Z',
     '1.0.0': '2018-02-16T14:45:22.088Z',
     modified: '2018-02-16T17:16:56.825Z' },
```

as the package-manager npm `newest` methor is 
```
newest: function (packageName) {
        return view(packageName, 'time')
            .then(_.keys)
            .then(_.last);
    },
```
then the the output of `_.keys` will be `['created', '1.0.0', 'modified']` and the last one, `modified` will be returned, hence breaking the application as that's not a valid version.

you can fix that by simply modify the newest function to 
```
newest: function (packageName) {
        return view(packageName, 'time')
            .then(_.keys)
            .then(_.partialRight(_.pullAll, ['modified', 'created']))
            .then(_.last);
    },
```
or something similar.
