### ISSUE TITLE
Cannot find module 'lodash._baseclone'

### ISSUE THREAD

**Issue by fdeitelhoff** [tjunnone/npm-check-updates#404]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 9.0.0
* npm version: 5.5.1
* npm-check-updates version: 2.13.0

---------------------------

I get this error when I call the "ncu" command:

```
Unhandled rejection Error: Cannot find module 'lodash._baseclone'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Fabia\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\node_modules\lodash.clonedeep\index.js:9:17)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Fabia\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\lib\fetch-package-metadata.js:15:13)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
```

ncu -v for example is working. But checking for upgradable npm packages isn't working.

I installed ncu via the command npm i -g npm-check-updates.

I've no idea how to fix or at least how to search for possible reasons in order how to fix it.

Did someone has/had this problem, too?

**Comment by raineorshine** [comment]
Unfortunately I am unable to reproduce. I would suggest uninstalling and then reinstalling, as npm sadly sometimes messes up the install.

**Comment by MadDeveloper** [comment]
I have exactly the same problem, I reinstalled the package with npm but the problem still persists.

**Comment by fdeitelhoff** [comment]
I reinstalled the package myself multiple times. The problem still exists.

**Comment by fdeitelhoff** [comment]
I tested it again: Removed the package and reinstalled it again within an admin powershell console. Now it seems to work... not quite sure why. :)

**Comment by kyle-ssg** [comment]
Can confirm in my case on osx ```npm remove npm-check-updates -g``` then ```npm i npm-check-updates -g``` fixes the issue
