### ISSUE TITLE
Unhandled rejection TypeError: cacheFile(...) is not a function

### ISSUE THREAD

**Issue by andregs** [tjunnone/npm-check-updates#419]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v8.9.1
* npm version: 5.5.1
* npm-check-updates version: 2.14.0

---------------------------

If I run ncu locally I get the following exception:
```
.\node_modules\.bin\npm-check-updates

Unhandled rejection TypeError: cacheFile(...) is not a function
    at CachingRegistryClient.get (C:\Users\me\workspace\project\node_modules\npm\lib\cache\caching-client.js:68:53)
    at C:\Users\me\workspace\project\node_modules\npm\lib\view.js:107:18
    at mapToRegistry (C:\Users\me\workspace\project\node_modules\npm\lib\utils\map-to-registry.js:62:3)
    at fetchAndRead (C:\Users\me\workspace\project\node_modules\npm\lib\view.js:104:3)
    at EventEmitter.view (C:\Users\me\workspace\project\node_modules\npm\lib\view.js:95:5)
    at Object.commandCache.(anonymous function) (C:\Users\me\workspace\project\node_modules\npm\lib\npm.js:124:13)
    at C:\Users\me\workspace\project\node_modules\npm-check-updates\lib\raw-promisify.js:22:31
    at Promise._execute (C:\Users\me\workspace\project\node_modules\bluebird\js\release\debuggability.js:303:9)
    at Promise._resolveFromExecutor (C:\Users\me\workspace\project\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Users\me\workspace\project\node_modules\bluebird\js\release\promise.js:79:10)
    at Object.obj.(anonymous function) [as viewAsync] (C:\Users\me\workspace\project\node_modules\npm-check-updates\lib\raw-promisify.js:14:20)
    at view (C:\Users\me\workspace\project\node_modules\npm-check-updates\lib\package-managers\npm.js:21:25)
    at C:\Users\me\workspace\project\node_modules\cint\cint.js:545:13
    at getPackageVersionProtected (C:\Users\me\workspace\project\node_modules\npm-check-updates\lib\versionmanager.js:356:16)
    at tryCatcher (C:\Users\me\workspace\project\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\me\workspace\project\node_modules\bluebird\js\release\map.js:61:38)
```

However if I run the same command via the global ncu binary then it works:

```ps
ncu

[..................] | :
 typescript  2.6.2  →  2.7.1

Run ncu with -u to upgrade package.json
```

I have installed ncu@2.14.0 both locally and globally.

Additional info:

```ps
npm ls -g --depth=0
C:\Users\me\AppData\Roaming\nvm\current
+-- @angular/cli@1.6.7
+-- npm@5.5.1
`-- npm-check-updates@2.14.0


npm ls npm
`-- npm-check-updates@2.14.0
  +-- npm@3.10.10
  `-- npmi@2.0.1
    `-- npm@3.10.10  deduped
```

**Comment by raineorshine** [comment]
Thanks for reporting! I am not actively working on `ncu` currently, but will hopefully be able to put some time back into the project in the future. In the mean time, if anyone else is interested in troubleshooting this that would be very helpful.

**Comment by andregs** [comment]
Thanks for your feedback. I was looking into the open PRs and I believe this issue will be solved when ncu gets rid of the local npm v3 dependency.
