### ISSUE TITLE
Unhandled rejection TypeError: dep.indexOf is not a function

### ISSUE THREAD

**Issue by luisesn** [tjunnone/npm-check-updates#441]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v9.11.1
* npm version: 6.1.0
* npm-check-updates version: 2.14.2
---------------------------

I've used ncu perfectly at my laptop, but trying to run it in my server gives this error:

Using /home/microservicios/trunk/modules/package.json
Unhandled rejection TypeError: dep.indexOf is not a function
    at /usr/lib/node_modules/npm-check-updates/lib/versionmanager.js:391:31
    at baseFindIndex (/usr/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:802:11)
    at findIndex (/usr/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:7258:14)
    at Function.find (/usr/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:5079:21)
    at /usr/lib/node_modules/npm-check-updates/lib/versionmanager.js:390:18
    at arrayAggregator (/usr/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:497:34)
    at Function.groupBy (/usr/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:4843:16)
    at getPreferredWildcard (/usr/lib/node_modules/npm-check-updates/lib/versionmanager.js:389:20)
    at upgradeDependencies (/usr/lib/node_modules/npm-check-updates/lib/versionmanager.js:119:20)
    at /usr/lib/node_modules/npm-check-updates/lib/versionmanager.js:222:36
    at tryCatcher (/usr/lib/node_modules/npm-check-updates/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm-check-updates/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/npm-check-updates/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/npm-check-updates/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/npm-check-updates/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/lib/node_modules/npm-check-updates/node_modules/bluebird/js/release/promise.js:638:18)

The package.json contents are:

microservicios@ubuntuRedis:~/trunk/modules$ cat package.json
{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "babel-runtime": {
      "version": "6.26.0",
      "resolved": "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz",
      "integrity": "sha1-llxwWGaOgrVde/4E/yM3vItWR/4=",
      "requires": {
        "core-js": "2.5.5",
        "regenerator-runtime": "0.11.1"
      }
    },
    "big-number": {
      "version": "0.3.1",
      "resolved": "https://registry.npmjs.org/big-number/-/big-number-0.3.1.tgz",
      "integrity": "sha1-rHMCDApZu3nrF8LOLbd/d9l04BM="
    },
    "bl": {
      "version": "1.2.2",
      "resolved": "https://registry.npmjs.org/bl/-/bl-1.2.2.tgz",
      "integrity": "sha512-e8tQYnZodmebYDWGH7KMRvtzKXaJHx3BbilrgZCfvyLUYdKpK1t5PSPmpkny/SgiTSCnjfLW7v5rlONXVFkQEA==",
      "requires": {
        "readable-stream": "2.3.6",
        "safe-buffer": "5.1.1"
      }
    },
    "core-js": {
      "version": "2.5.5",
      "resolved": "https://registry.npmjs.org/core-js/-/core-js-2.5.5.tgz",
      "integrity": "sha1-sU3ek2xkDAV5prUMq8wTLdYSfjs="
    },
    "core-util-is": {
      "version": "1.0.2",
      "resolved": "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz",
      "integrity": "sha1-tf1UIgqivFq1eqtxQMlAdUUDwac="
    },
    "debug": {
      "version": "2.6.9",
      "resolved": "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz",
      "integrity": "sha512-bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==",
      "requires": {
        "ms": "2.0.0"
      }
    },
    "depd": {
      "version": "1.1.2",
      "resolved": "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz",
      "integrity": "sha1-m81S4UwJd2PnSbJ0xDRu0uVgtak="
    },
    "generic-pool": {
      "version": "3.4.2",
      "resolved": "https://registry.npmjs.org/generic-pool/-/generic-pool-3.4.2.tgz",
      "integrity": "sha512-H7cUpwCQSiJmAHM4c/aFu6fUfrhWXW1ncyh8ftxEPMu6AiYkHw9K8br720TGPZJbk5eOH2bynjZD1yPvdDAmag=="
    },
    "iconv-lite": {
      "version": "0.4.21",
      "resolved": "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.21.tgz",
      "integrity": "sha512-En5V9za5mBt2oUA03WGD3TwDv0MKAruqsuxstbMUZaj9W9k/m1CV/9py3l0L5kw9Bln8fdHQmzHSYtvpvTLpKw==",
      "requires": {
        "safer-buffer": "2.1.2"
      }
    },
    "inherits": {
      "version": "2.0.3",
      "resolved": "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz",
      "integrity": "sha1-Yzwsg+PaQqUC9SRmAiSA9CCCYd4="
    },
    "isarray": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz",
      "integrity": "sha1-u5NdSFgsuhaMBoNJV6VKPgcSTxE="
    },
    "ms": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz",
      "integrity": "sha1-VgiurfwAvmwpAd9fmGF4jeDVl8g="
    },
    "mssql": {
      "version": "4.1.0",
      "resolved": "https://registry.npmjs.org/mssql/-/mssql-4.1.0.tgz",
      "integrity": "sha512-ekht0eILEV0P1CbpkwpAxhgO+/5goYizUJrt7pgDm3fP6lGKe0+8V9jhTvQZ8DPHkycSd0wYGUoz/YA7VN7kQQ==",
      "requires": {
        "debug": "2.6.9",
        "generic-pool": "3.4.2",
        "tedious": "2.3.1"
      }
    },
    "process-nextick-args": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz",
      "integrity": "sha512-MtEC1TqN0EU5nephaJ4rAtThHtC86dNN9qCuEhtshvpVBkAW5ZO7BASN9REnF9eoXGcRub+pFuKEpOHE+HbEMw=="
    },
    "readable-stream": {
      "version": "2.3.6",
      "resolved": "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz",
      "integrity": "sha512-tQtKA9WIAhBF3+VLAseyMqZeBjW0AHJoxOtYqSUZNJxauErmLbVm2FW1y+J/YA9dUrAC39ITejlZWhVIwawkKw==",
      "requires": {
        "core-util-is": "1.0.2",
        "inherits": "2.0.3",
        "isarray": "1.0.0",
        "process-nextick-args": "2.0.0",
        "safe-buffer": "5.1.1",
        "string_decoder": "1.1.1",
        "util-deprecate": "1.0.2"
      }
    },
    "regenerator-runtime": {
      "version": "0.11.1",
      "resolved": "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.1.tgz",
      "integrity": "sha512-MguG95oij0fC3QV3URf4V2SDYGJhJnJGqvIIgdECeODCT98wSWDAJ94SSuVpYQUoTcGUIL6L4yNB7j1DFFHSBg=="
    },
    "safe-buffer": {
      "version": "5.1.1",
      "resolved": "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz",
      "integrity": "sha512-kKvNJn6Mm93gAczWVJg7wH+wGYWNrDHdWvpUmHyEsgCtIwwo3bqPtV4tR5tuPaUhTOo/kvhVwd8XwwOllGYkbg=="
    },
    "safer-buffer": {
      "version": "2.1.2",
      "resolved": "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz",
      "integrity": "sha512-YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg=="
    },
    "sprintf": {
      "version": "0.1.5",
      "resolved": "https://registry.npmjs.org/sprintf/-/sprintf-0.1.5.tgz",
      "integrity": "sha1-j4PjmpMXwaUCy324BQ5Rxnn27c8="
    },
    "string_decoder": {
      "version": "1.1.1",
      "resolved": "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz",
      "integrity": "sha512-n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==",
      "requires": {
        "safe-buffer": "5.1.1"
      }
    },
    "tedious": {
      "version": "2.3.1",
      "resolved": "https://registry.npmjs.org/tedious/-/tedious-2.3.1.tgz",
      "integrity": "sha512-aJkmYFzoVf0X/M0yNyYETfWfuaYsK/cWqekf/EGnvYoLENVqL1ATdAVLNZdA7TmZLfWxKf70JLr3h9inki+9zQ==",
      "requires": {
        "babel-runtime": "6.26.0",
        "big-number": "0.3.1",
        "bl": "1.2.2",
        "depd": "1.1.2",
        "iconv-lite": "0.4.21",
        "readable-stream": "2.3.6",
        "sprintf": "0.1.5"
      }
    },
    "util-deprecate": {
      "version": "1.0.2",
      "resolved": "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz",
      "integrity": "sha1-RQ1Nyfpw3nMnYvvS1KKJgUGaDM8="
    }
  }
}

**Comment by raineorshine** [comment]
Interesting! That shouldn't happen, although I am not sure what is being returned in the dependency object that would make `dep.indexOf` not a function.

Could you could add the following line of code to line 391 of  `/usr/lib/node_modules/npm-check-updates/lib/versionmanager.js` (right before `return dep && dep.indexOf(wildcard) > -1;`) and post what you get? That would be super helpful!

```
if (dep && !dep,.indexOf) { console.log('DEBUG', dep) }
```

**Comment by luisesn** [comment]
Of course (I've deleted a comma that didn't belong ;) )

microservicios@ubuntuRedis:~/trunk/modules$ ncu
Using /home/microservicios/trunk/modules/package.json
DEBUG { version: 'latest',
  resolved: 'https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz',
  integrity: 'sha1-llxwWGaOgrVde/4E/yM3vItWR/4=',
  requires: { 'core-js': 'latest', 'regenerator-runtime': 'latest' } }
Unhandled rejection TypeError: dep.indexOf is not a function

**Comment by raineorshine** [comment]
@luisesn Thank you!

It appears that your `package.json` is not a proper package.json at all. Could your `package-lock.json` accidentally have copied over your `package.json`?

**Comment by luisesn** [comment]
That it is indeed a possibility, I'm out of "work" for a few days, I'll recreate the package.json when I'm back.

Thanks!

**Comment by ykhandor** [comment]
Did you figure the issue here? If not, is there a functionality in your code by which you create a new folder and append files/folders to it once you run the npm command?

**Comment by raineorshine** [comment]
Closing due to inactivity. Please comment with steps to reproduce if this is still an issue.
