### ISSUE TITLE
stdin test failure in node 8

### ISSUE THREAD

**Issue by raineorshine** [tjunnone/npm-check-updates#448]
```
1) npm-check-updates cli should handle no package.json to analyze when receiving empty 
content on stdin:
     AssertionError: expected npm WARN invalid config loglevel="notice"
No package.json
Please add a package.json to the current directory, specify the --packageFile or 
--packageData options, or pipe a package.json to stdin. to start with No package.json
      at test/test-ncu.js:106:53
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:689:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

https://travis-ci.org/tjunnone/npm-check-updates/jobs/398231487

**Comment by raineorshine** [comment]
All tests are passing on the v3 branch now for node 8, 10, and 11.

https://travis-ci.org/tjunnone/npm-check-updates/builds/482186035

**Comment by Astikai** [comment]
how do i curl that

**Comment by Astikai** [comment]
i'm usung chrome deb
