### ISSUE TITLE
Unable to authenticate, need: Bearer 

### ISSUE THREAD

**Issue by rwieruch** [tjunnone/npm-check-updates#565]
* node version: 10.16.0
* npm version: 6.10.0
* npm-check-updates version: 3.1.18

---------------------------

I upgraded from 3.1.13 to 3.1.18. and get the following error message [0] for my `ncu` command now.

[0]

```
Checking /Users/user/Developer/Repos/treact-ui/template/package.json
[--------------------] 0/31 0%/Users/user/.nvm/versions/node/v10.16.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:387
        throw err;
        ^

Error: Unable to authenticate, need: Bearer authorization_uri=https://login.windows.net/db4cfc4c-4ec7-41df-8bfe-b9f4983df1dc, Basic realm="https://pkgsprodsu3weu.app.pkgs.visualstudio.com/", TFS-Federated
    at res.buffer.catch.then.body (/Users/user/.nvm/versions/node/v10.16.0/lib/node_modules/npm-check-updates/node_modules/npm-registry-fetch/check-response.js:94:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by rwieruch** [comment]
Closed in favor of https://github.com/tjunnone/npm-check-updates/issues/556
