### ISSUE TITLE
ncu stops with a syntax error

### ISSUE THREAD

**Issue by AmarBouchibane** [tjunnone/npm-check-updates#617]
- [ x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [ x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 6.17.1
* npm version: 3.10.10
* npm-check-updates version: 3.2.0

---------------------------
When running "ncu" I get this syntax error:
C:\Program Files\nodejs-6\node_modules\npm-check-updates\node_modules\update-notifier\index.js:74
                        (async () => {
                               ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files\nodejs-6\node_modules\npm-check-updates\bin\ncu:6:24)

**Comment by stoically** [comment]
[Minimum node version to use ncu is 8.](https://github.com/tjunnone/npm-check-updates/blob/0706633f9251d37ce458bc62ba985c2ec5905ffd/package.json#L27-L29)
