### ISSUE TITLE
blocker! TypeError: undefined is not a function

### ISSUE THREAD

**Issue by gitowiec** [tjunnone/npm-check-updates#89]
I installed unstable version on Windoze 7 (npm install -g npm-check-updates@unstable) and after running 'ncu' i got:

```
$ ncu
You can now use "ncu" for less typing!
c:\Users\Marek\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\lib\utils\correct-mkdir.js:37
    var uid = +process.getuid()
                       ^
TypeError: undefined is not a function
    at calculateOwner (c:\Users\Marek\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\lib\utils\corrct-mkdir.js:37:24)
    at c:\Users\Marek\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm\lib\utils\correct-mkdir.js:23:22
    at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
```

**Comment by mathieumg** [comment]
This is an `npm` problem that was fixed in https://github.com/npm/npm/releases/tag/v2.12.1, but still marked as being a pre-release.

**Comment by gitowiec** [comment]
I rapidly switched to npm-check-updates@1.5.1 and it is fine now, I use it with ember-cli. Thanks for great module!

**Comment by metaraine** [comment]
Thanks Mathieu. I will pull in v2.12.1.
